// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECWxdBkdvvAiHG4H851yfRnNoVUucwBI',
    appId: '1:894091766054:android:aee7539d23466e323bf9e7',
    messagingSenderId: '894091766054',
    projectId: 'movies-bd6ed',
    storageBucket: 'movies-bd6ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6ZsHMMpisO9qFZfLCawsOot8sYsfhps',
    appId: '1:894091766054:ios:b877ded9953b31c73bf9e7',
    messagingSenderId: '894091766054',
    projectId: 'movies-bd6ed',
    storageBucket: 'movies-bd6ed.firebasestorage.app',
    androidClientId: '894091766054-3etgd13go47hkdtuh0lvpc03tgtpuhrl.apps.googleusercontent.com',
    iosClientId: '894091766054-rmrfg4vo4jm2kqm23ddso90f7uh8t43a.apps.googleusercontent.com',
    iosBundleId: 'com.dragon.moviesApp',
  );
}
